  Enumeration 1 ; RNet_Mail_Attribute
    #RNet_Mail_Attribute_ReturnPath
    #RNet_Mail_Attribute_DeliveredTo
    #RNet_Mail_Attribute_Received
    #RNet_Mail_Attribute_XSender
    #RNet_Mail_Attribute_XMailer
    #RNet_Mail_Attribute_XUser
    #RNet_Mail_Attribute_XScript
    #RNet_Mail_Attribute_Date
    #RNet_Mail_Attribute_From
    #RNet_Mail_Attribute_BCC
    #RNet_Mail_Attribute_Subject
    #RNet_Mail_Attribute_XProxadSc
    #RNet_Mail_Attribute_XSpamCheckerVersion
    #RNet_Mail_Attribute_XSpamLevel
    #RNet_Mail_Attribute_XSpamStatus
    #RNet_Mail_Attribute_To
    #RNet_Mail_Attribute_ReplyTo
    #RNet_Mail_Attribute_XAuthSmtpUser
    #RNet_Mail_Attribute_XAbuseContact
    #RNet_Mail_Attribute_MimeVersion
    #RNet_Mail_Attribute_ContentType
    #RNet_Mail_Attribute_MessageId
    #RNet_Mail_Attribute_DomainkeySignature
    #RNet_Mail_Attribute_Organization
    #RNet_Mail_Attribute_XPriority
    #RNet_Mail_Attribute_UserAgent
    #RNet_Mail_Attribute_ThreadTopic
    #RNet_Mail_Attribute_ThreadIndex
    #RNet_Mail_Attribute_XEmvCampagneid
    #RNet_Mail_Attribute_XEmvMemberid
  EndEnumeration
  
  Structure S_RNet_Mail
    Infos_to.s
    Infos_cc.s
    Infos_bcc.s
    Infos_from.s
    Infos_date.s
    Infos_subject.s
    Infos_reply_to.s
    Infos_return_path.s
    Infos_delivered_to.s
    Infos_received.s
    Infos_mime_version.s
    Infos_content_type.s
    Infos_message_id.s
    Infos_domainkey_signature.s
    Infos_organization.s
    Infos_user_agent.s
    Infos_thread_topic.s
    Infos_thread_index.s
    Infos_x_sender.s
    Infos_x_mailer.s
    Infos_x_user.s
    Infos_x_script.s
    Infos_x_proxad_sc.s
    Infos_x_spam_checker_version.s
    Infos_x_spam_level.s
    Infos_x_spam_status.s
    Infos_x_auth_smtp_user.s
    Infos_x_abuse_contact.s
    Infos_x_priority.s
    Infos_x_emv_campagneid.s
    Infos_x_emv_memberid.s
    Infos_path.s
    Infos_newsgroups.s
    Infos_references.s
    Infos_content_transfer_encoding.s
    Infos_lines.s
    Infos_nntp_posting_date.s
    Infos_nntp_posting_host.s
    Infos_x_trace.s
    Infos_x_complaints_to.s
    Infos_xref.s
    Infos_Body.s
  EndStructure